# NumPy Overview

NumPy stands for **Numerical Python**. It is one of the most important Python libraries for scientific computing and numerical operations.

NumPy provides a powerful object called the **ndarray** (N-dimensional array), which allows fast and efficient storage and manipulation of numeric data.


## 1. Why NumPy Is Important

NumPy is widely used because it is:
- faster than normal Python lists for numerical computation
- memory efficient
- easy to use for matrix and array operations
- the foundation for libraries like pandas, SciPy, scikit-learn, and matplotlib

In many data science and machine learning workflows, NumPy is a core dependency.


## 2. Installation and Import

Install NumPy using pip:

```bash
pip install numpy
```

Import NumPy using the standard alias `np`:

```python
import numpy as np
```


## 3. What Is a NumPy Array?

A NumPy array is a collection of elements of the same data type stored in a structured and efficient form.

Compared to Python lists:
- NumPy arrays are faster for computation
- they support vectorized operations
- they allow advanced indexing, broadcasting, and reshaping


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


## 4. Dimensions in NumPy Arrays

NumPy arrays can have multiple dimensions:
- 1D array: a simple list-like structure
- 2D array: rows and columns like a matrix
- 3D array: multiple matrices stacked together


In [2]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print("1D array:\n", arr1)
print("2D array:\n", arr2)
print("3D array:\n", arr3)


1D array:
 [1 2 3]
2D array:
 [[1 2 3]
 [4 5 6]]
3D array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## 5. Important Array Attributes

Useful array attributes include:
- `ndim`: number of dimensions
- `shape`: size of each dimension
- `size`: total number of elements
- `dtype`: data type of elements
- `itemsize`: size of each element in bytes


In [ ]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data type:", arr.dtype)
print("Item size:", arr.itemsize)


## 6. Common Ways to Create Arrays

NumPy provides several convenient functions to create arrays.


In [ ]:
import numpy as np

print(np.zeros((2, 3)))
print(np.ones((2, 2)))
print(np.full((2, 2), 7))
print(np.eye(3))
print(np.arange(0, 10, 2))
print(np.linspace(0, 1, 5))


## 7. Indexing and Slicing

NumPy arrays support indexing and slicing similar to Python lists, but with more power for multidimensional data.


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])


In [ ]:
import numpy as np

arr2d = np.array([[1, 2, 3], [4, 5, 6]])

print(arr2d[0, 1])
print(arr2d[:, 1])
print(arr2d[1, :])


## 8. Vectorized Operations

One of the biggest advantages of NumPy is vectorization.

Vectorization means performing operations on entire arrays without writing explicit Python loops.

This makes code shorter, cleaner, and faster.


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a - b)
print(a * b)
print(a / b)


## 9. Broadcasting

Broadcasting allows NumPy to perform operations on arrays of different shapes when they are compatible.

This avoids manual looping and makes numerical computation more efficient.


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr + 10)


## 10. Mathematical Functions

NumPy provides many built-in mathematical functions that operate element-wise on arrays.


In [4]:
import numpy as np

arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.sum(arr))
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))


[1. 2. 3. 4.]
30
7.5
16
1


## 11. Reshaping Arrays

Reshaping changes the structure of the array without changing its data.

The total number of elements must remain the same.


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped = arr.reshape(2, 3)

print(arr)
print(reshaped)


## 12. Flattening Arrays

Flattening converts a multidimensional array into a one-dimensional array.


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())


## 13. Copy vs View

This is an important NumPy concept.

- A **copy** creates a new array with separate data.
- A **view** references the original array data.

Changing a view may affect the original array.


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])
view_arr = arr.view()
copy_arr = arr.copy()

arr[0] = 100

print("Original:", arr)
print("View:", view_arr)
print("Copy:", copy_arr)


## 14. Random Module in NumPy

NumPy provides random number generation utilities that are widely used in simulations, testing, and machine learning.


In [ ]:
import numpy as np

print(np.random.rand(3))
print(np.random.randint(1, 10, size=(2, 3)))


## 15. Boolean Indexing and Filtering

Boolean indexing allows selection of elements based on conditions.

This is very useful for data cleaning and filtering tasks.


In [ ]:
import numpy as np

arr = np.array([10, 15, 20, 25, 30])
print(arr[arr > 18])


## 16. Aggregation Functions

Aggregation functions summarize array data.

Common functions:
- `sum()`
- `mean()`
- `median()`
- `std()`
- `var()`
- `min()`
- `max()`


In [ ]:
import numpy as np

arr = np.array([5, 10, 15, 20])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard deviation:", np.std(arr))


## 17. Working with Axes

In multidimensional arrays, operations can be performed along a specific axis.

For a 2D array:
- `axis=0` means operation column-wise
- `axis=1` means operation row-wise


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Column sums:", np.sum(arr, axis=0))
print("Row sums:", np.sum(arr, axis=1))


## 18. NumPy Arrays vs Python Lists

| Feature | Python List | NumPy Array |
| --- | --- | --- |
| Speed | Slower for numeric operations | Faster |
| Memory usage | Higher | Lower |
| Element type | Can store mixed types | Usually same type |
| Mathematical operations | Limited | Powerful and vectorized |
| Multidimensional support | Basic | Strong |


## 19. Applications of NumPy

NumPy is used in:
- data analysis
- machine learning
- image processing
- scientific computing
- simulations
- linear algebra
- statistics


## 20. Best Practices

- prefer vectorized operations over loops when possible
- choose appropriate data types for memory efficiency
- understand array shapes before performing operations
- use broadcasting carefully to avoid unintended results
- use copies when you do not want changes to affect the original data


## 21. Mini Example

The example below combines creation, arithmetic, filtering, and aggregation.


In [1]:
import numpy as np

marks = np.array([45, 67, 89, 32, 76, 91])

print("Original marks:", marks)
print("Bonus added:", marks + 5)
print("Passed students:", marks[marks >= 40])
print("Average marks:", np.mean(marks))
print("Highest marks:", np.max(marks))


Original marks: [45 67 89 32 76 91]
Bonus added: [50 72 94 37 81 96]
Passed students: [45 67 89 76 91]
Average marks: 66.66666666666667
Highest marks: 91


## 22. Summary

NumPy is the foundation of numerical computing in Python.

It provides:
- fast and efficient arrays
- vectorized computation
- broadcasting
- reshaping and indexing tools
- mathematical and statistical functions

A strong understanding of NumPy makes it much easier to work with data science, machine learning, and scientific Python libraries.
